---
- hosts: windows-hosts
  gather_facts: no
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: zeroday.local
      hostname: zd-ws-01
      domain_admin_user: Administrator@zeroday.local
      domain_admin_password: Seclab123!
      state: domain
    register: domain_state
  - win_reboot:
      msg: "Domain joined. Rebooting"
      pre_reboot_delay: 15
      when: domain_state.changed