---
- name: Create Domain Users
  hosts: domaincontrollers
  tasks:
  - name: Create Domain Groups
    community.windows.win_domain_group:
      name: "{{ item.name }}"
      state: present
    loop:
      "{{ groups }}"
  - name: Create Domain Users
    community.windows.win_domain_user:
      firstname: "{{ item.firstName }}"
      lastname: "{{ item.lastName }}"
      name: "{{ item.username }}"
      password: "{{ item.password }}"
    loop:
      "{{ users }}"
  vars:
    users:
      - firstName: "Joe"
        lastName: "HackMe"
        username: "jhackme"
        password: "Winter2022!"
      - firstName: "Jane"
        lastName: "Pwnerson"
        username: "jpwnerson"
        password: "Eureka4791?"
      - firstName: "Adam"
        lastName: "Minerva"
        username: "aminerva"
        password: "!M1n3rv4!"
        groups:
          - "Domain Admins"
    groups:
      - name: "IT Staff"
      - name: "Marketing"
      - name: "Accounting"
      - name: "HR"
      - name: "Software Developers"
      