- name: Install Unzip
  ansible.builtin.apt:
    name: unzip
    state: latest

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/latest.zip

- name: Install WordPress
  unarchive:
    src: /tmp/latest.zip
    dest: /var/www/html/
    owner: www-data
    group: www-data

- name: Cleanup Install Files 1
  file: 
    path: /tmp/wordpress
    state: absent

- name: Cleanup Install Files 2
  file:
    path: /tmp/latest.zip
    state: absent
