- name: Confirm Communication
  ansible.windows.win_powershell:
    script: | 
      "Get-ComputerInfo"
- name: Set upstream DNS server 
  win_dns_client:
    adapter_names: 'Ethernet 2'
    ipv4_addresses:
     - '{{ upstream_dns_1 }}'
     - '{{ upstream_dns_2 }}'

- name: Disable Firewall
  win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public

- name: Change the hostname
  win_hostname:
    name: '{{ dc_hostname }}'
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: Install Active Directory
  win_feature: >
    name=AD-Domain-Services
    include_management_tools=yes
    include_sub_features=yes
    state=present
  register: result

- name: Create Domain
  win_domain:
    dns_domain_name: '{{ domain_name }}'
    safe_mode_password: '{{ recovery_password }}'
  register: ad

- name: Reboot Server
  win_reboot:
    msg: "Install AD. Rebooting"
    pre_reboot_delay: 15
  when: ad.changed

- name: Set internal DNS server
  win_dns_client:
    adapter_names: "Ethernet 2"
    ipv4_addresses:
    - '127.0.0.1'

- name: Create reverse DNS zone
  win_shell: "Add-DnsServerPrimaryZone -NetworkID {{ reverse_dns_zone }} -ReplicationScope Forest"
  retries: 30
  delay: 60
  register: result
  until: result is succeeded
