- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Install PHP
  ansible.builtin.apt:
    name: php
    state: latest

- name: Install PHP-mysql
  ansible.builtin.apt:
    name: php-mysql
    state: latest

- name: Install MySQL
  ansible.builtin.apt:
    name: mysql-server
    state: latest
