---
- name: Confirm Prereqs
  ansible.builtin.apt:
    name: ["ca-certificates", "curl", "gnupg", "lsb-release" ]
    update_cache: yes

- name: Add Docker GPG Key
  ansible.builtin.shell:
    cmd: curl -L https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add Docker Sources
  ansible.builtin.shell: 
    cmd: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install Docker Engine
  ansible.builtin.apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
    update_cache: yes

- name: Add Seclab to Docker
  ansible.builtin.user:
    groups: docker
    append: yes
    name: seclab
